name: plugin-mc
version: 1.0
main: org.plugins.pluginmc.Main
api-version: '1.20'
author: roquv13
commands:
  help:
    description: Display information about commands in plugin
    usage: /help
    permission: plugin-mc.help
    permission-message: You don't have permission to use /help

  itemshop:
    description: Using item shop in game
    usage: /itemshop or /itemshop [player] [item]
    permission: plugin-mc.itemshop
    permission-message: You don't have permission to use /itemshop

  effects:
    description: Set up effects to player
    usage: /effects [player]
    permission: plugin-mc.effects
    permission-message: You don't have permission to use /effects

permissions:
  help:
    description: Allows you to get infomations about plugin
    default: true

  itemshop:
    description: Allows you to use itemshop
    default: true

  effects:
    description: Allows you to use effects given to player
    default: true