name: plugin-mc
version: 1.0
main: org.plugins.pluginmc.Main
api-version: '1.20'
author: roquv13
commands:
  help:
    description: Display information about commands in plugin
    usage: /help
    permission: plugin-mc.help
    permission-message: You don't have permission to use /help

  itemshop:
    description: Using item shop in game
    usage: /itemshop or /itemshop [player] [item]
    permission: plugin-mc.itemshop
    permission-message: You don't have permission to use /itemshop

  effects:
    description: Set up effects to player
    usage: /effects [player]
    permission: plugin-mc.effects
    permission-message: You don't have permission to use /effects

  chat:
    description: Chat ON/OFF/CLEAR
    usage: /chat on/off/clear
    permission: plugin-mc.chat
    permission-message: You don't have permission to use /chat

  vanish:
    description: Make visible or invisible
    usage: /vanish
    permission: plugin-mc.vanish
    permission-message: You don't have permission to use /vanish

  drop:
    description: Enable or disable drop
    usage: /drop
    permission: plugin-mc.drop
    permission-message: You don't have permission to use /drop

  warp:
    description: Open warp Gui
    usage: /warp or /warp [add/del] [warp name] or /warp list
    permission: plugin-mc.warp
    permission-message: You don't have permission to use /warp

  home:
    description: Teleport to players home
    usage: /home [home name/list]
    permission: plugin-mc.home
    permission-message: You don't have permission to use /home

  sethome:
    description: Set up new home for player
    usage: /sethome [home name]
    permission: plugin-mc.sethome
    permission-message: You don't have permission to use /sethome

  delhome:
    description: Delete player home
    usage: /delhome [home name]
    permission: plugin-mc.delhome
    permission-message: You don't have permission to use /delhome

  gm:
    description: Set up gamemode to player
    usage: /gm [0/1/2/3/4]
    permission: plugin-mc.gm
    permission-message: You don't have permission to use /gm

permissions:
  help:
    description: Allows you to get infomations about plugin
    default: true

  itemshop:
    description: Allows you to use itemshop
    default: true

  effects:
    description: Allows you to use effects given to player
    default: true

  chat:
    description: Allows you to turn on/off chat
    default: true

  vanish:
    description: Allows you to use hide you
    default: true

  drop:
    description: Allows you to change drops of items when you dig up
    default: true

  warp:
    description: Allows you to use teleport to locations
    default: true